# Generated by Django 3.0.6 on 2020-05-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a news genre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('article', models.TextField(help_text='Enter article')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this news', to='news.Genre')),
            ],
        ),
    ]
